// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKs11m6aZeaO6a2EedqRWXxJWTo0Lk7o',
    appId: '1:564501308576:web:3b51f6d61f22d2609455c5',
    messagingSenderId: '564501308576',
    projectId: 'swivel-event-planner-43bc7',
    authDomain: 'swivel-event-planner-43bc7.firebaseapp.com',
    storageBucket: 'swivel-event-planner-43bc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChBaXnfOi6Q-sycT-04Y63f8TQ_-zKULc',
    appId: '1:564501308576:android:f7aecf71360d5f809455c5',
    messagingSenderId: '564501308576',
    projectId: 'swivel-event-planner-43bc7',
    storageBucket: 'swivel-event-planner-43bc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JpBEHGH8t2ce5-YRZ9zzoAXQiXNzxyc',
    appId: '1:564501308576:ios:bd6063fe75b1903d9455c5',
    messagingSenderId: '564501308576',
    projectId: 'swivel-event-planner-43bc7',
    storageBucket: 'swivel-event-planner-43bc7.firebasestorage.app',
    iosBundleId: 'dev.lasith.eventplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JpBEHGH8t2ce5-YRZ9zzoAXQiXNzxyc',
    appId: '1:564501308576:ios:bd6063fe75b1903d9455c5',
    messagingSenderId: '564501308576',
    projectId: 'swivel-event-planner-43bc7',
    storageBucket: 'swivel-event-planner-43bc7.firebasestorage.app',
    iosBundleId: 'dev.lasith.eventplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLKs11m6aZeaO6a2EedqRWXxJWTo0Lk7o',
    appId: '1:564501308576:web:7b2830ff3957ea839455c5',
    messagingSenderId: '564501308576',
    projectId: 'swivel-event-planner-43bc7',
    authDomain: 'swivel-event-planner-43bc7.firebaseapp.com',
    storageBucket: 'swivel-event-planner-43bc7.firebasestorage.app',
  );
}
